{% set name = "ipympl" %}
{% set version = "0.9.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6d7230d518384521093f3854f7db89d069dcd9c28a935b371e9c9f126354dee1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -v
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    # Needed for setup process
    - yarn
    - hatchling
    - jupyterlab ==4.*
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder >=0.8.3
  run:
    - python
    - ipython <10
    - ipywidgets >=7.6.0,<9
    - matplotlib-base >=3.5.0,<4
    - numpy
    - pillow
    - traitlets <6

test:
  source_files:
    - tests
  imports:
    - ipympl
  commands:
    - pip check
    - pytest -v tests
    - test -f ${PREFIX}/share/jupyter/nbextensions/jupyter-matplotlib/extension.js  # [unix]
    - test -f ${PREFIX}/share/jupyter/nbextensions/jupyter-matplotlib/index.js  # [unix]
    - test -f ${PREFIX}/share/jupyter/labextensions/jupyter-matplotlib/package.json  # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\jupyter-matplotlib\\extension.js (exit 1)  # [win]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\jupyter-matplotlib\\index.js (exit 1)  # [win]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\jupyter-matplotlib\\package.json (exit 1)  # [win]
  requires:
    - pip
    - pytest
    - importlib_metadata

about:
  home: https://github.com/matplotlib/ipympl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Matplotlib Jupyter Extension
  description: Matplotlib Jupyter Extension
  dev_url: https://github.com/matplotlib/ipympl
  doc_url: https://matplotlib.org/ipympl

extra:
  recipe-maintainers:
    - JasonGrout
    - SylvainCorlay
    - tacaswell
    - blink1073
    - martinRenou