{% set version = "0.6.3" %}
{% set sha256 = "bf2a33863ec9025d6d767f09b9f36dd8f7fe80d1f8f5ba08fca9f4e460ee64f8" %}

package:
    name: ipympl
    version: {{ version }}

source:
    fn: ipympl-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/i/ipympl/ipympl-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 0
    noarch: python
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python
        - setuptools
        - jupyter
        - pip
    run:
        - python
        - ipywidgets >=7.5.0,<8.0
        - ipykernel >=4.7
        - matplotlib >=2.2.0
        - six

test:
    imports:
        - ipympl

about:
    home: https://github.com/matplotlib/jupyter-matplotlib
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Matplotlib Jupyter Extension

extra:
  recipe-maintainers:
    - JasonGrout
    - SylvainCorlay
    - tacaswell
    - blink1073
    - martinRenou
