travis:
  secure:
    BINSTAR_TOKEN: fCXOLDVnlowFpFjVFqXMhzIgQ4+u/CCfoo7peunNQux8raBJ29a5NRH+C8rBRcBoFsGc48M36m318DbXciEo+I5R2WdnuSKebpxne+IovcitSfKrdQp+z+m/EAVMHysSsJg6lrXakqNTavymBj8/ISmewAP/Ws24TC7wZ8IMo3BU7hVfmQJ3SkbBEqsnWpLPEE5wL/jYtyhhu9FkvXB7tCBTuHI8pkYilRviKkfTM1Iu0m6+ieuqsHgXJEB+hV+TqtXoFZr3kfLyFBGVM14UwItrg65CvLlD7fXpirtC1CpgkjSM5+4I2CJFddsmt/BZBKk9s+zFLK67cIV35U+jJqT3Y9YJo3UldmgfxsJZgkn2ApaqTZSYY46wvP37ijJs98cx0ToNqAS6O5UiCl+2xtXJ49817FSwNZJondLhRnvHbBVgsHum1uKMA+jNsCraYyW/YcIgY+4gp9Xq3ukhvYV2+5nB4LjpbhwP20QPgYTFWEAF8EQVXnlTrgOxUZKBzlayOC4oyjs2S+c9ibA3CNFjtT47ruR9arJsJooYI/xeCW30atDRJBCHmnsX+eUO7RdvipabsMBjGb/Y6uBhqN2VcuLZEK8t/ope3Tsocj39Ku3CfX2ovkp5VEsxuey9E5t6YvOtSff+1IUVgatrxtKHsK3GgwB4Vj6qj00A/50=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
