travis:
  secure:
    BINSTAR_TOKEN: O6NYqaDs9h6XuDsS9lRzEfDnSQYcptq/4ADabQI91FPy9qE14b58IIGwdoSmAkPKOKaLvSXcUk0NnuhCMqfqBUxbF0qIZcr7MURoz89fG07F9UsUFhdk0DFTBBCj/MiXtj6228W+ZxcG6QFWlhp+kFZegSjaUZ/vQtW4y6hNXSa7oxSLp5w8wME+PzfK5eh6Wo2hhAp8xkS1JY84KrhtluE2fhXj0nUfbe55c55USDhWMDrDqazRz3Ru9hjJQRgynGvK7pd6wqCzfNFb5s1J+26ejpCH7ZM/3rZMNVixBTVnjyOKHsACbS3SV7ohoSQfCEuSfHFDgmtY1xERBONOqe2YYY1ZCjuqtAcB1+sqmjIyoXVPxWKZLQ9u1h52srnmxiPyCX9xalu/lZS+MqFsXok1KBxBtM7WVNz/qvJ9KHBsWiHH9WaKRQxyexGHLnDyFLhY1pi3ztQ6+JtVZQIDRn+oVwyUZnOUeLopJkb7efA9EgU7h66aBBdEF8f3x3bcPZ1wBMYFLTZuOs/I2yhvtgNzNhBC7pntPVxajM8hJMuZPt1+Rb+tYS4BR2CWP9Az2/anBqFas+cMZxOnY/IaZTc2dCqg9ZjwL8OlXLptpd1w2h+H7eqkJ+m2uX5kQxbhfbIDFTxCO2vBNskQlm//tM5nJBQlrCWcJZ2HzT+R8jk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
